In [36]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/sajazhr/Hotel Reservations.csv


part 1

In [37]:
import pandas as pd
from graphviz import Source
from sklearn.tree import DecisionTreeClassifier, export_graphviz


In [38]:
apears = pd.read_csv('/kaggle/input/sajazhr/Hotel Reservations.csv',index_col="Booking_ID")

y=apears.pop("booking_status").values
x=apears.values
print(x)
print(y)
apears.shape
apears.head()

[[2 0 1 ... 0 65.0 0]
 [2 0 2 ... 0 106.68 1]
 [1 0 2 ... 0 60.0 0]
 ...
 [2 0 2 ... 0 98.39 2]
 [2 0 0 ... 0 94.5 0]
 [2 0 1 ... 0 161.67 0]]
['Not_Canceled' 'Not_Canceled' 'Canceled' ... 'Not_Canceled' 'Canceled'
 'Not_Canceled']


no_of_adults  no_of_children  no_of_weekend_nights  \
Booking_ID                                                       
INN00001               2               0                     1   
INN00002               2               0                     2   
INN00003               1               0                     2   
INN00004               2               0                     0   
INN00005               2               0                     1   

            no_of_week_nights type_of_meal_plan  required_car_parking_space  \
Booking_ID                                                                    
INN00001                    2       Meal Plan 1                           0   
INN00002                    3      Not Selected                           0   
INN00003                    1       Meal Plan 1                           0   
INN00004                    2       Meal Plan 1                           0   
INN00005                    1      Not Selected                           0   

           room_type_reserved  lead_time  arrival_year  arrival_month  \
Booking_ID                                                              
INN00001          Room_Type 1        224          2017             10   
INN00002          Room_Type 1          5          2018             11   
INN00003          Room_Type 1          1          2018              2   
INN00004          Room_Type 1        211          2018              5   
INN00005          Room_Type 1         48          2018              4   

            arrival_date market_segment_type  repeated_guest  \
Booking_ID                                                     
INN00001               2             Offline               0   
INN00002               6              Online               0   
INN00003              28              Online               0   
INN00004              20              Online               0   
INN00005              11              Online               0   

            no_of_previous_cancellations  \
Booking_ID                                 
INN00001                               0   
INN00002                               0   
INN00003                               0   
INN00004                               0   
INN00005                               0   

            no_of_previous_bookings_not_canceled  avg_price_per_room  \
Booking_ID                                                             
INN00001                                       0               65.00   
INN00002                                       0              106.68   
INN00003                                       0               60.00   
INN00004                                       0              100.00   
INN00005                                       0               94.50   

            no_of_special_requests  
Booking_ID                          
INN00001                         0  
INN00002                         1  
INN00003                         0  
INN00004                         0  
INN00005                         0

What is the dataset's shape? (36275, 17)
How many samples are there? 36275
How many features are there? 17
How many categorical features are there in the dataset? 3
What is the distribution of the target label "booking_status"?


In [39]:
import numpy as np
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, random_state = 100)
print(X_train)

[[2 0 1 ... 0 216.0 0]
 [1 0 2 ... 0 61.0 0]
 [2 0 1 ... 0 144.0 0]
 ...
 [2 0 0 ... 0 75.0 1]
 [1 0 0 ... 0 81.0 0]
 [2 0 0 ... 0 109.8 1]]


In [40]:
tree = DecisionTreeClassifier(criterion='entropy')
ap_tree = tree.fit(X_train, y_train)
predictions = ap_tree.predict(X_test)
print(predictions[:5])
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predictions))


ValueError: could not convert string to float: 'Meal Plan 1'

the data not fitting because there is categorical data. we must remove categorical data and x be numerical

In [41]:
apears.pop('type_of_meal_plan')
apears.pop('room_type_reserved')
apears.pop('market_segment_type')
x=apears.values


In [42]:
import numpy as np
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, random_state = 100)
print(X_train)

[[  2.    0.    1.  ...   0.  216.    0. ]
 [  1.    0.    2.  ...   0.   61.    0. ]
 [  2.    0.    1.  ...   0.  144.    0. ]
 ...
 [  2.    0.    0.  ...   0.   75.    1. ]
 [  1.    0.    0.  ...   0.   81.    0. ]
 [  2.    0.    0.  ...   0.  109.8   1. ]]


In [43]:
tree = DecisionTreeClassifier(criterion='entropy')
ap_tree = tree.fit(X_train, y_train)


In [44]:
from sklearn.metrics import accuracy_score
predictions = ap_tree.predict(X_test)
print(predictions[:5])
print(accuracy_score(y_test, predictions))


['Not_Canceled' 'Not_Canceled' 'Not_Canceled' 'Not_Canceled' 'Canceled']
0.8541184254052266


accuracy good after remove categorical data and x be numerical

In [45]:
from sklearn.model_selection import GridSearchCV

params = {
    'criterion':  ['gini', 'entropy'],
    'max_depth':  [None, 2, 4, 6, 8, 10],
    'max_features': [None, 'sqrt', 'log2', 0.2, 0.4, 0.6, 0.8],
    'splitter': ['best', 'random']
}

clf = GridSearchCV(
    estimator=DecisionTreeClassifier(),
    param_grid=params,
    cv=5,
    n_jobs=5,
    verbose=1,
)
clf.fit(X_train, y_train)
print(clf.best_params_)



Fitting 5 folds for each of 168 candidates, totalling 840 fits
{'criterion': 'entropy', 'max_depth': None, 'max_features': 0.8, 'splitter': 'best'}


What is the best values for 
'criterion'=entropy
 'max_depth'=none
 'max_features'=0.6
 'splitter'=best

In [48]:
clf = DecisionTreeClassifier(max_depth=4, criterion='entropy', max_features=0.6, splitter='best')
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)
print(accuracy_score(y_test, predictions))


0.7935825339067152


accuracy good

part 2

In [53]:
apears = pd.read_csv('/kaggle/input/sajazhr/Hotel Reservations.csv',index_col="Booking_ID")
y=apears.pop("booking_status").values
X=apears.values
print(X)
print(y)
apears.head()

[[2 0 1 ... 0 65.0 0]
 [2 0 2 ... 0 106.68 1]
 [1 0 2 ... 0 60.0 0]
 ...
 [2 0 2 ... 0 98.39 2]
 [2 0 0 ... 0 94.5 0]
 [2 0 1 ... 0 161.67 0]]
['Not_Canceled' 'Not_Canceled' 'Canceled' ... 'Not_Canceled' 'Canceled'
 'Not_Canceled']


no_of_adults  no_of_children  no_of_weekend_nights  \
Booking_ID                                                       
INN00001               2               0                     1   
INN00002               2               0                     2   
INN00003               1               0                     2   
INN00004               2               0                     0   
INN00005               2               0                     1   

            no_of_week_nights type_of_meal_plan  required_car_parking_space  \
Booking_ID                                                                    
INN00001                    2       Meal Plan 1                           0   
INN00002                    3      Not Selected                           0   
INN00003                    1       Meal Plan 1                           0   
INN00004                    2       Meal Plan 1                           0   
INN00005                    1      Not Selected                           0   

           room_type_reserved  lead_time  arrival_year  arrival_month  \
Booking_ID                                                              
INN00001          Room_Type 1        224          2017             10   
INN00002          Room_Type 1          5          2018             11   
INN00003          Room_Type 1          1          2018              2   
INN00004          Room_Type 1        211          2018              5   
INN00005          Room_Type 1         48          2018              4   

            arrival_date market_segment_type  repeated_guest  \
Booking_ID                                                     
INN00001               2             Offline               0   
INN00002               6              Online               0   
INN00003              28              Online               0   
INN00004              20              Online               0   
INN00005              11              Online               0   

            no_of_previous_cancellations  \
Booking_ID                                 
INN00001                               0   
INN00002                               0   
INN00003                               0   
INN00004                               0   
INN00005                               0   

            no_of_previous_bookings_not_canceled  avg_price_per_room  \
Booking_ID                                                             
INN00001                                       0               65.00   
INN00002                                       0              106.68   
INN00003                                       0               60.00   
INN00004                                       0              100.00   
INN00005                                       0               94.50   

            no_of_special_requests  
Booking_ID                          
INN00001                         0  
INN00002                         1  
INN00003                         0  
INN00004                         0  
INN00005                         0

In [58]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer


# use make_column_transformer and OneHotEncoder to convert categorical features to numbers
column_transformer = make_column_transformer((OneHotEncoder(), ['type_of_meal_plan', 'room_type_reserved', 'market_segment_type']), remainder='passthrough')
X_transformed = column_transformer.fit_transform(apears.iloc[:, :-1])
X_transformed = pd.DataFrame(data=X_transformed)


# split dataset to train/test split
X_train, X_test, y_train, y_test = train_test_split(X_transformed, y, test_size=0.2, random_state=100)



In [59]:
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)

predictions = clf.predict(X_test)
print(accuracy_score(y_test, predictions))


0.8146106133700896


How accurate is the model? good
Does the model improve by using categorical features? yes